backend:
  name: git-gateway
  repo: brianmugunga/kwanwebsite_final
  branch: main
  base_url: https://elegant-heliotrope-5da109.netlify.app
  auth_endpoint: /.netlify/functions/auth

# Optional: for local development
local_backend: true

# Publish mode: either 'editorial_workflow' for drafts, or 'simple' for direct publish
publish_mode: editorial_workflow

# Media files configuration
media_folder: "public/uploads"
public_folder: "/uploads"

# Collections define the structure for the different content types
collections:
  # Blog Posts
  - name: "blog"
    label: "Blog Posts"
    folder: "public/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Dr. Kwan-Lamar Blount-Hill" }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  # Publications
  - name: "publications"
    label: "Publications"
    folder: "public/content/publications"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Authors", name: "authors", widget: "string" }
      - { label: "Publication Type", name: "type", widget: "select", options: ["Journal Article", "Book", "Book Chapter", "Conference Paper", "Other"] }
      - { label: "Year", name: "year", widget: "number", value_type: "int" }
      - { label: "Journal/Publisher", name: "venue", widget: "string" }
      - { label: "Volume", name: "volume", widget: "string", required: false }
      - { label: "Issue", name: "issue", widget: "string", required: false }
      - { label: "Pages", name: "pages", widget: "string", required: false }
      - { label: "DOI", name: "doi", widget: "string", required: false }
      - { label: "PDF Link", name: "pdf_link", widget: "string", required: false }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Abstract", name: "abstract", widget: "text" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Research Areas", name: "research_areas", widget: "list", required: false }

  # Research Projects
  - name: "research"
    label: "Research Projects"
    folder: "public/content/research"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Status", name: "status", widget: "select", options: ["Current", "Completed", "Upcoming"] }
      - { label: "Start Date", name: "start_date", widget: "datetime", required: false }
      - { label: "End Date", name: "end_date", widget: "datetime", required: false }
      - { label: "Funding Source", name: "funding", widget: "string", required: false }
      - { label: "Funding Amount", name: "funding_amount", widget: "string", required: false }
      - { label: "Collaborators", name: "collaborators", widget: "list", required: false }
      - { label: "Institution", name: "institution", widget: "string", required: false }
      - { label: "Research Areas", name: "research_areas", widget: "list", required: false }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Key Findings", name: "findings", widget: "markdown", required: false }
      - { label: "Related Publications", name: "related_publications", widget: "list", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }

  # Service Activities
  - name: "service"
    label: "Service & Community"
    folder: "public/content/service"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Academic Service", "Professional Membership", "Community Engagement", "Editorial Board", "Conference Organization", "Other"] }
      - { label: "Organization", name: "organization", widget: "string" }
      - { label: "Role", name: "role", widget: "string", required: false }
      - { label: "Start Date", name: "start_date", widget: "datetime", required: false }
      - { label: "End Date", name: "end_date", widget: "datetime", required: false }
      - { label: "Ongoing", name: "ongoing", widget: "boolean", default: false }
      - { label: "Description", name: "description", widget: "markdown" }

  # Teaching
  - name: "teaching"
    label: "Teaching"
    folder: "public/content/teaching"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Course Title", name: "title", widget: "string" }
      - { label: "Course Code", name: "course_code", widget: "string", required: false }
      - { label: "Institution", name: "institution", widget: "string" }
      - { label: "Semester/Term", name: "term", widget: "string" }
      - { label: "Year", name: "year", widget: "number", value_type: "int" }
      - { label: "Level", name: "level", widget: "select", options: ["Undergraduate", "Graduate", "Both"] }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Syllabus", name: "syllabus", widget: "file", required: false }

  # CV Data (structured data for CV page)
  - name: "cv_data"
    label: "CV Data"
    files:
      - label: "Education"
        name: "education"
        file: "public/content/cv/education.json"
        fields:
          - label: "Education Entries"
            name: "entries"
            widget: "list"
            fields:
              - { label: "Degree", name: "degree", widget: "string" }
              - { label: "Field", name: "field", widget: "string", required: false }
              - { label: "Institution", name: "institution", widget: "string" }
              - { label: "Location", name: "location", widget: "string", required: false }
              - { label: "Year", name: "year", widget: "string" }
              - { label: "Details", name: "details", widget: "text", required: false }

      - label: "Professional Experience"
        name: "experience"
        file: "public/content/cv/experience.json"
        fields:
          - label: "Experience Entries"
            name: "entries"
            widget: "list"
            fields:
              - { label: "Position", name: "position", widget: "string" }
              - { label: "Institution/Organization", name: "institution", widget: "string" }
              - { label: "Location", name: "location", widget: "string", required: false }
              - { label: "Start Date", name: "start_date", widget: "string" }
              - { label: "End Date", name: "end_date", widget: "string", required: false }
              - { label: "Current", name: "current", widget: "boolean", default: false }
              - { label: "Description", name: "description", widget: "text", required: false }

      - label: "Awards & Honors"
        name: "awards"
        file: "public/content/cv/awards.json"
        fields:
          - label: "Award Entries"
            name: "entries"
            widget: "list"
            fields:
              - { label: "Award Name", name: "name", widget: "string" }
              - { label: "Organization", name: "organization", widget: "string" }
              - { label: "Year", name: "year", widget: "string" }
              - { label: "Description", name: "description", widget: "text", required: false }

      - label: "Skills"
        name: "skills"
        file: "public/content/cv/skills.json"
        fields:
          - label: "Skill Categories"
            name: "categories"
            widget: "list"
            fields:
              - { label: "Category Name", name: "name", widget: "string" }
              - { label: "Skills", name: "skills", widget: "list" }

  # Site Settings
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "public/content/settings/general.json"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
          - { label: "Site Description", name: "site_description", widget: "text" }
          - { label: "Contact Email", name: "contact_email", widget: "string" }
          - { label: "Location", name: "location", widget: "string" }
          - { label: "LinkedIn URL", name: "linkedin_url", widget: "string", required: false }
          - { label: "Twitter/X URL", name: "twitter_url", widget: "string", required: false }
          - { label: "Academia.edu URL", name: "academia_url", widget: "string", required: false }
          - { label: "ResearchGate URL", name: "researchgate_url", widget: "string", required: false }

      - label: "Home Page"
        name: "home"
        file: "public/content/settings/home.json"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
          - { label: "Hero Introduction", name: "hero_intro", widget: "text" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
          - label: "Statistics"
            name: "stats"
            widget: "list"
            fields:
              - { label: "Value", name: "value", widget: "string" }
              - { label: "Label", name: "label", widget: "string" }

      - label: "About Page"
        name: "about"
        file: "public/content/settings/about.json"
        fields:
          - { label: "Personal Statement", name: "personal_statement", widget: "text" }
          - { label: "Professional Biography", name: "bio", widget: "markdown" }
          - { label: "Photo", name: "photo", widget: "image" }
          - label: "Personal Values"
            name: "values"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
